# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75a6fea08af31387d607f1a5d19230fa5547c3d797349207dd7d0c00edfcd7712ec9890b7c922ae2f7e59ebc7de6cb81f9d21cd0db0fadd258f378204c4a843c

test:
  secret_key_base: 0857d13d3c6d1dcd3d3e84114ea54c9a90988534c3de1993738177137f674e36cfefd5efb74da88f8c8602a1e64cee675beec9a64d2fd9ca99e580e440960e38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
